INSERT INTO CLIENTE (NOME)
VALUES ('Apple Inc.');

INSERT INTO CLIENTE (NOME)
VALUES ('Google');

INSERT INTO CLIENTE (NOME)
VALUES ('Microsoft');

INSERT INTO CLIENTE (NOME)
VALUES ('Tesla');

INSERT INTO CLIENTE (NOME)
VALUES ('SpaceX');

COMMIT;
