INSERT INTO MODULO (NOME)
VALUES ('Financeiro');

INSERT INTO MODULO (NOME)
VALUES ('Vendas');

INSERT INTO MODULO (NOME)
VALUES ('Expedição');

INSERT INTO MODULO (NOME)
VALUES ('Foguetes');

COMMIT;